---
layout: cv
title: R. Carlos Lamas CV
---
# Carlos Lamas
Graduate Financial Economics Student <br>
Minor In Data Science 

<div id="webaddress">
<a href="https://www.linkedin.com/in/carlos-lamas-8323a2251/">LinkedIn Profile</a>
</div>


## Currently

Seeking Employment in Investment Research 

### Specialized in

Developed a strong understanding of financial economics that required analytical and quantitative skills. 


### Research interests

Alternative Investing, Real Estate Finance, Algorithmic Trading. 


## Education

`2020 - 2024`<br>
__BYU-I, Bachelor Degree in Financial Economics__



## Experience 
`June 2021 - August 2023`<br>
Etrade Financial <br>
• Resolved customer's problems dealing with issues related to stock and options trade <br>
• Offered guidance on utilizing E*TRADE trading platforms for technical analysis, charts, executing trades <br>
• Facilitated opening accounts for a variety of clients, including day traders to high-net-worth individuals<br>
• Educated customer on a general retirement contribution, Roth conversions, and recharacterizations <br>
• Reviewed suspicious activity of money laundering. Identity theft and account takeovers<br>
• Guided customers in processing bank wires and facilitating account transfers internally and externally <br>

## Additional Information 
• Data Wrangling and Visualization: Preformed data analysis by cleaning and transforming data sets <br>
• Problem-Solving: Developed analytic and critical thinking skills to break down complex problems  <br>
• Data Visualization: Visualization skills in R, power point and Excel<br>
• Programming: Strong programming skills in R, python <br>
• Certifications: Bloomberg Certification, Harvard Excel certification in Excel <br>
• Languages: Fluent in Spanish <br>
• Interests: Creating personal investment models, trading options, cooking, serving in the church, following sports<br>
• Work Eligibility: Eligible to work in the U.S. with no restrictions  <br>

### Leadership, Activities, License 	 						             		           	
• Leadership: Activity sought out team members at E*TRADE who needed help with clients’ inquiries related to trading concepts, tax issues, and fraud-related questions. <br>
• License: Previously licensed with Series 7, Series 63, and SIE through E*TRADE<br>




<!-- ### Footer

Last updated: April 2024 -->

